CREATE TABLE tblCountry(
    idCountry VARCHAR(5) NOT NULL,
    dtCountry VARCHAR(50) NOT NULL,
    dtPhoneCode INT,
    dtImage VARCHAR(200),
    PRIMARY KEY (idCountry)
);

INSERT INTO tblCountry (idCountry, dtCountry, dtPhoneCode, dtImage)
VALUES  ('AF', 'Afghanistan', 93, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/270px-Flag_of_the_Taliban.svg.png'),
        ('AX', 'Aland Islands', 358, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Flag_of_%C3%85land.svg/188px-Flag_of_%C3%85land.svg.png'),
        ('AL', 'Albania', 355, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/188px-Flag_of_Albania.svg.png'),
        ('DZ', 'Algeria', 213, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/188px-Flag_of_Algeria.svg.png'),
        ('AS', 'American Samoa', 1684, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/195px-Flag_of_American_Samoa.svg.png'),
        ('AD', 'Andorra', 376, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/188px-Flag_of_Andorra.svg.png'),
        ('AO', 'Angola', 244, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/188px-Flag_of_Angola.svg.png'),
        ('AI', 'Anguilla', 1264, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/195px-Flag_of_Anguilla.svg.png'),
        ('AQ', 'Antarctica', 672, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg/2560px-Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg.png'),
        ('AG', 'Antigua and Barbuda', 1268, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/188px-Flag_of_Antigua_and_Barbuda.svg.png'),
        ('AR', 'Argentina', 54, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/188px-Flag_of_Argentina.svg.png'),
        ('AM', 'Armenia', 374, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/188px-Flag_of_Armenia.svg.png'),
        ('AW', 'Aruba', 297, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/188px-Flag_of_Aruba.svg.png'),
        ('AU', 'Australia', 61, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/188px-Flag_of_Australia_%28converted%29.svg.png'),
        ('AT', 'Austria', 43, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/188px-Flag_of_Austria.svg.png'),
        ('AZ', 'Azerbaijan', 994, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/188px-Flag_of_Azerbaijan.svg.png'),
        ('BS', 'Bahamas', 1242, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/188px-Flag_of_the_Bahamas.svg.png'),
        ('BH', 'Bahrain', 973, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/188px-Flag_of_Bahrain.svg.png'),
        ('BD', 'Bangladesh', 880, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/188px-Flag_of_Bangladesh.svg.png'),
        ('BB', 'Barbados', 1246, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/188px-Flag_of_Barbados.svg.png'),
        ('BY', 'Belarus', 375, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/188px-Flag_of_Belarus.svg.png'),
        ('BE', 'Belgium', 32, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/188px-Flag_of_Belgium.svg.png'),
        ('BZ', 'Belize', 501, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/188px-Flag_of_Belize.svg.png'),
        ('BJ', 'Benin', 229, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/188px-Flag_of_Benin.svg.png'),
        ('BM', 'Bermuda', 1441, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/195px-Flag_of_Bermuda.svg.png'),
        ('BT', 'Bhutan', 975, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/188px-Flag_of_Bhutan.svg.png'),
        ('BO', 'Bolivia', 591, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/188px-Flag_of_Bolivia.svg.png'),
        ('BQ', 'Bonaire, Sint Eustatius and Saba', 599, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_Bonaire.svg/188px-Flag_of_Bonaire.svg.png'),
        ('BA', 'Bosnia and Herzegovina', 387, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/195px-Flag_of_Bosnia_and_Herzegovina.svg.png'),
        ('BW', 'Botswana', 267, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/188px-Flag_of_Botswana.svg.png'),
        ('BV', 'Bouvet Island', 55, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/32px-Flag_of_Norway.svg.png'),
        ('BR', 'Brazil', 55, 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/188px-Flag_of_Brazil.svg.png'),
        ('IO', 'British Indian Ocean Territory', 246, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg/195px-Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg.png'),
        ('BN', 'Brunei Darussalam', 673, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/188px-Flag_of_Brunei.svg.png'),
        ('BG', 'Bulgaria', 359, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/188px-Flag_of_Bulgaria.svg.png'),
        ('BF', 'Burkina Faso', 226, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/188px-Flag_of_Burkina_Faso.svg.png'),
        ('BI', 'Burundi', 257, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/188px-Flag_of_Burundi.svg.png'),
        ('KH', 'Cambodia', 855, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/188px-Flag_of_Cambodia.svg.png'),
        ('CM', 'Cameroon', 237, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/188px-Flag_of_Cameroon.svg.png'),
        ('CA', 'Canada', 1, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/188px-Flag_of_Canada_%28Pantone%29.svg.png'),
        ('CV', 'Cape Verde', 238, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/188px-Flag_of_Cape_Verde.svg.png'),
        ('KY', 'Cayman Islands', 1345, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/195px-Flag_of_the_Cayman_Islands.svg.png'),
        ('CF', 'Central African Republic', 236, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/188px-Flag_of_the_Central_African_Republic.svg.png'),
        ('TD', 'Chad', 235, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/188px-Flag_of_Chad.svg.png'),
        ('CL', 'Chile', 56, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/188px-Flag_of_Chile.svg.png'),
        ('CN', 'China', 86, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/188px-Flag_of_the_People%27s_Republic_of_China.svg.png'),
        ('CX', 'Christmas Island', 61, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flag_of_Christmas_Island.svg/195px-Flag_of_Christmas_Island.svg.png'),
        ('CC', 'Cocos (Keeling) Islands', 672, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg/195px-Flag_of_the_Cocos_%28Keeling%29_Islands.svg.png'),
        ('CO', 'Colombia', 57, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/188px-Flag_of_Colombia.svg.png'),
        ('KM', 'Comoros', 269, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/188px-Flag_of_the_Comoros.svg.png'),
        ('CG', 'Congo', 242, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/188px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png'),
        ('CD', 'Congo, Democratic Republic of the Congo', 242, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/188px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png'),
        ('CK', 'Cook Islands', 682, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/188px-Flag_of_the_Cook_Islands.svg.png'),
        ('CR', 'Costa Rica', 506, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/188px-Flag_of_Costa_Rica.svg.png'),
        ('CI', 'Cote D""Ivoire', 225, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/188px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png'),
        ('HR', 'Croatia', 385, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/188px-Flag_of_Croatia.svg.png'),
        ('CU', 'Cuba', 53, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/188px-Flag_of_Cuba.svg.png'),
        ('CW', 'Curacao', 599, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_Cura%C3%A7ao.svg/188px-Flag_of_Cura%C3%A7ao.svg.png'),
        ('CY', 'Cyprus', 357, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/188px-Flag_of_Cyprus.svg.png'),
        ('CZ', 'Czech Republic', 420, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/188px-Flag_of_the_Czech_Republic.svg.png'),
        ('DK', 'Denmark', 45, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/180px-Flag_of_Denmark.svg.png'),
        ('DJ', 'Djibouti', 253, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/188px-Flag_of_Djibouti.svg.png'),
        ('DM', 'Dominica', 1767, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/188px-Flag_of_Dominica.svg.png'),
        ('DO', 'Dominican Republic', 1809, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/188px-Flag_of_the_Dominican_Republic.svg.png'),
        ('EC', 'Ecuador', 593, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/188px-Flag_of_Ecuador.svg.png'),
        ('EG', 'Egypt', 20, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/188px-Flag_of_Egypt.svg.png'),
        ('SV', 'El Salvador', 503, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/270px-Flag_of_El_Salvador.svg.png'),
        ('GQ', 'Equatorial Guinea', 240, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/188px-Flag_of_Equatorial_Guinea.svg.png'),
        ('ER', 'Eritrea', 291, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/188px-Flag_of_Eritrea.svg.png'),
        ('EE', 'Estonia', 372, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/188px-Flag_of_Estonia.svg.png'),
        ('ET', 'Ethiopia', 251, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/188px-Flag_of_Ethiopia.svg.png'),
        ('FK', 'Falkland Islands (Malvinas)', 500, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/195px-Flag_of_the_Falkland_Islands.svg.png'),
        ('FO', 'Faroe Islands', 298, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/188px-Flag_of_the_Faroe_Islands.svg.png'),
        ('FJ', 'Fiji', 679, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/188px-Flag_of_Fiji.svg.png'),
        ('FI', 'Finland', 358, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/188px-Flag_of_Finland.svg.png'),
        ('FR', 'France', 33, 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/188px-Flag_of_France.svg.png'),
        ('GF', 'French Guiana', 594, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Coat_of_arms_of_French_Guiana%2C_according_to_the_original_displayed_at_the_Museum_Franconie%2C_at_Cayenne.svg/180px-Coat_of_arms_of_French_Guiana%2C_according_to_the_original_displayed_at_the_Museum_Franconie%2C_at_Cayenne.svg.png'),
        ('PF', 'French Polynesia', 689, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/188px-Flag_of_French_Polynesia.svg.png'),
        ('TF', 'French Southern Territories', 262, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Flag_of_the_French_Southern_and_Antarctic_Lands.svg/188px-Flag_of_the_French_Southern_and_Antarctic_Lands.svg.png'),
        ('GA', 'Gabon', 241, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/188px-Flag_of_Gabon.svg.png'),
        ('GM', 'Gambia', 220, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/188px-Flag_of_The_Gambia.svg.png'),
        ('GE', 'Georgia', 995, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/188px-Flag_of_Georgia.svg.png'),
        ('DE', 'Germany', 49, 'https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/188px-Flag_of_Germany.svg.png'),
        ('GH', 'Ghana', 233, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/188px-Flag_of_Ghana.svg.png'),
        ('GI', 'Gibraltar', 350, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/195px-Flag_of_Gibraltar.svg.png'),
        ('GR', 'Greece', 30, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/188px-Flag_of_Greece.svg.png'),
        ('GL', 'Greenland', 299, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/195px-Flag_of_Greenland.svg.png'),
        ('GD', 'Grenada', 1473, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/188px-Flag_of_Grenada.svg.png'),
        ('GP', 'Guadeloupe', 590, 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2f/Guadaloupe_logo.svg/135px-Guadaloupe_logo.svg.png'),
        ('GU', 'Guam', 1671, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/195px-Flag_of_Guam.svg.png'),
        ('GT', 'Guatemala', 502, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/188px-Flag_of_Guatemala.svg.png'),
        ('GG', 'Guernsey', 44, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Guernsey.svg/188px-Flag_of_Guernsey.svg.png'),
        ('GN', 'Guinea', 224, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/188px-Flag_of_Guinea.svg.png'),
        ('GW', 'Guinea-Bissau', 245, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/188px-Flag_of_Guinea-Bissau.svg.png'),
        ('GY', 'Guyana', 592, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/188px-Flag_of_Guyana.svg.png'),
        ('HT', 'Haiti', 509, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/188px-Flag_of_Haiti.svg.png'),
        ('HM', 'Heard Island and Mcdonald Islands', 0, 'https://flagpedia.net/data/flags/w580/hm.png'),
        ('VA', 'Holy See (Vatican City State)', 39, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Flag_of_the_Vatican_City_%282023%E2%80%93present%29.svg/188px-Flag_of_the_Vatican_City_%282023%E2%80%93present%29.svg.png'),
        ('HN', 'Honduras', 504, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/188px-Flag_of_Honduras.svg.png'),
        ('HK', 'Hong Kong', 852, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/188px-Flag_of_Hong_Kong.svg.png'),
        ('HU', 'Hungary', 36, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/188px-Flag_of_Hungary.svg.png'),
        ('IS', 'Iceland', 354, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/188px-Flag_of_Iceland.svg.png'),
        ('IN', 'India', 91, 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/188px-Flag_of_India.svg.png'),
        ('ID', 'Indonesia', 62, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/188px-Flag_of_Indonesia.svg.png'),
        ('IR', 'Iran', 98, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/188px-Flag_of_Iran.svg.png'),
        ('IQ', 'Iraq', 964, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/188px-Flag_of_Iraq.svg.png'),
        ('IE', 'Ireland', 353, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/1200px-Flag_of_Ireland.svg.png'),
        ('IM', 'Isle of Man', 44, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_the_Isle_of_Man.svg/210px-Flag_of_the_Isle_of_Man.svg.png'),
        ('IL', 'Israel', 972, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/188px-Flag_of_Israel.svg.png'),
        ('IT', 'Italy', 39, 'https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/188px-Flag_of_Italy.svg.png'),
        ('JM', 'Jamaica', 1876, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/188px-Flag_of_Jamaica.svg.png'),
        ('JP', 'Japan', 81, 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/188px-Flag_of_Japan.svg.png'),
        ('JE', 'Jersey', 44, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Flag_of_Jersey.svg/188px-Flag_of_Jersey.svg.png'),
        ('JO', 'Jordan', 962, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/188px-Flag_of_Jordan.svg.png'),
        ('KZ', 'Kazakhstan', 7, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Kazakhstan_%28President_of_Kazakhstan_website%29.svg/203px-Flag_of_Kazakhstan_%28President_of_Kazakhstan_website%29.svg.png'),
        ('KE', 'Kenya', 254, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/188px-Flag_of_Kenya.svg.png'),
        ('KI', 'Kiribati', 686, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/188px-Flag_of_Kiribati.svg.png'),
        ('KP', 'Korea, North', 850, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/188px-Flag_of_North_Korea.svg.png'),
        ('KR', 'Korea, South', 82, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/188px-Flag_of_South_Korea.svg.png'),
        ('XK', 'Kosovo', 383, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Kosovo.svg/188px-Flag_of_Kosovo.svg.png'),
        ('KW', 'Kuwait', 965, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/188px-Flag_of_Kuwait.svg.png'),
        ('KG', 'Kyrgyzstan', 996, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/188px-Flag_of_Kyrgyzstan.svg.png'),
        ('LA', 'Lao People""s Democratic Republic', 856, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/188px-Flag_of_Laos.svg.png'),
        ('LV', 'Latvia', 371, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/188px-Flag_of_Latvia.svg.png'),
        ('LB', 'Lebanon', 961, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/188px-Flag_of_Lebanon.svg.png'),
        ('LS', 'Lesotho', 266, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/188px-Flag_of_Lesotho.svg.png'),
        ('LR', 'Liberia', 231, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/188px-Flag_of_Liberia.svg.png'),
        ('LY', 'Libya', 218, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/188px-Flag_of_Libya.svg.png'),
        ('LI', 'Liechtenstein', 423, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/188px-Flag_of_Liechtenstein.svg.png'),
        ('LT', 'Lithuania', 370, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/188px-Flag_of_Lithuania.svg.png'),
        ('LU', 'Luxembourg', 352, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/188px-Flag_of_Luxembourg.svg.png'),
        ('MO', 'Macao', 853, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/188px-Flag_of_Macau.svg.png'),
        ('MK', 'Macedonia, the Former Yugoslav Republic of', 389, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/188px-Flag_of_North_Macedonia.svg.png'),
        ('MG', 'Madagascar', 261, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/188px-Flag_of_Madagascar.svg.png'),
        ('MW', 'Malawi', 265, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/188px-Flag_of_Malawi.svg.png'),
        ('MY', 'Malaysia', 60, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/188px-Flag_of_Malaysia.svg.png'),
        ('MV', 'Maldives', 960, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/188px-Flag_of_Maldives.svg.png'),
        ('ML', 'Mali', 223, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/188px-Flag_of_Mali.svg.png'),
        ('MT', 'Malta', 356, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/188px-Flag_of_Malta.svg.png'),
        ('MH', 'Marshall Islands', 692, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/188px-Flag_of_the_Marshall_Islands.svg.png'),
        ('MQ', 'Martinique', 596, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag-of-Martinique.svg/188px-Flag-of-Martinique.svg.png'),
        ('MR', 'Mauritania', 222, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/188px-Flag_of_Mauritania.svg.png'),
        ('MU', 'Mauritius', 230, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/188px-Flag_of_Mauritius.svg.png'),
        ('YT', 'Mayotte', 262, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Coat_of_Arms_of_Mayotte.PNG/195px-Coat_of_Arms_of_Mayotte.PNG'),
        ('MX', 'Mexico', 52, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/188px-Flag_of_Mexico.svg.png'),
        ('FM', 'Micronesia, Federated States of', 691, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/375px-Flag_of_the_Federated_States_of_Micronesia.svg.png'),
        ('MD', 'Moldova, Republic of', 373, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/188px-Flag_of_Moldova.svg.png'),
        ('MC', 'Monaco', 377, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/180px-Flag_of_Monaco.svg.png'),
        ('MN', 'Mongolia', 976, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/188px-Flag_of_Mongolia.svg.png'),
        ('ME', 'Montenegro', 382, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/188px-Flag_of_Montenegro.svg.png'),
        ('MS', 'Montserrat', 1664, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/195px-Flag_of_Montserrat.svg.png'),
        ('MA', 'Morocco', 212, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/188px-Flag_of_Morocco.svg.png'),
        ('MZ', 'Mozambique', 258, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/188px-Flag_of_Mozambique.svg.png'),
        ('MM', 'Myanmar', 95, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/188px-Flag_of_Myanmar.svg.png'),
        ('NA', 'Namibia', 264, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/188px-Flag_of_Namibia.svg.png'),
        ('NR', 'Nauru', 674, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/188px-Flag_of_Nauru.svg.png'),
        ('NP', 'Nepal', 977, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/143px-Flag_of_Nepal.svg.png'),
        ('NL', 'Netherlands', 31, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/188px-Flag_of_the_Netherlands.svg.png'),
        ('AN', 'Netherlands Antilles', 599, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Flag_of_the_Netherlands_Antilles_%281959%E2%80%931986%29.svg/188px-Flag_of_the_Netherlands_Antilles_%281959%E2%80%931986%29.svg.png'),
        ('NC', 'New Caledonia', 687, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flags_of_New_Caledonia.svg/263px-Flags_of_New_Caledonia.svg.png'),
        ('NZ', 'New Zealand', 64, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/188px-Flag_of_New_Zealand.svg.png'),
        ('NI', 'Nicaragua', 505, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/188px-Flag_of_Nicaragua.svg.png'),
        ('NE', 'Niger', 227, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/150px-Flag_of_Niger.svg.png'),
        ('NG', 'Nigeria', 234, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/195px-Flag_of_Nigeria.svg.png'),
        ('NU', 'Niue', 683, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/188px-Flag_of_Niue.svg.png'),
        ('NF', 'Norfolk Island', 672, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/195px-Flag_of_Norfolk_Island.svg.png'),
        ('MP', 'Northern Mariana Islands', 1670, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/195px-Flag_of_the_Northern_Mariana_Islands.svg.png'),
        ('NO', 'Norway', 47, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/188px-Flag_of_Norway.svg.png'),
        ('OM', 'Oman', 968, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/188px-Flag_of_Oman.svg.png'),
        ('PK', 'Pakistan', 92, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/188px-Flag_of_Pakistan.svg.png'),
        ('PW', 'Palau', 680, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/188px-Flag_of_Palau.svg.png'),
        ('PS', 'Palestinian Territory, Occupied', 970, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/383px-Flag_of_Palestine.svg.png'),
        ('PA', 'Panama', 507, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/188px-Flag_of_Panama.svg.png'),
        ('PG', 'Papua New Guinea', 675, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/188px-Flag_of_Papua_New_Guinea.svg.png'),
        ('PY', 'Paraguay', 595, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/188px-Flag_of_Paraguay.svg.png'),
        ('PE', 'Peru', 51, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/188px-Flag_of_Peru.svg.png'),
        ('PH', 'Philippines', 63, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/195px-Flag_of_the_Philippines.svg.png'),
        ('PN', 'Pitcairn', 64, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_the_Pitcairn_Islands.svg/195px-Flag_of_the_Pitcairn_Islands.svg.png'),
        ('PL', 'Poland', 48, 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/188px-Flag_of_Poland.svg.png'),
        ('PT', 'Portugal', 351, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/188px-Flag_of_Portugal.svg.png'),
        ('PR', 'Puerto Rico', 1787, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/188px-Flag_of_Puerto_Rico.svg.png'),
        ('QA', 'Qatar', 974, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/203px-Flag_of_Qatar.svg.png'),
        ('RE', 'Reunion', 262, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Proposed_flag_of_R%C3%A9union_%28VAR%29.svg/300px-Proposed_flag_of_R%C3%A9union_%28VAR%29.svg.png'),
        ('RO', 'Romania', 40, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/188px-Flag_of_Romania.svg.png'),
        ('RU', 'Russian Federation', 7, 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/188px-Flag_of_Russia.svg.png'),
        ('RW', 'Rwanda', 250, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/188px-Flag_of_Rwanda.svg.png'),
        ('BL', 'Saint Barthelemy', 590, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg/300px-Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg.png'),
        ('SH', 'Saint Helena', 290, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Saint_Helena.svg/195px-Flag_of_Saint_Helena.svg.png'),
        ('KN', 'Saint Kitts and Nevis', 1869, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/383px-Flag_of_Saint_Kitts_and_Nevis.svg.png'),
        ('LC', 'Saint Lucia', 1758, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/188px-Flag_of_Saint_Lucia.svg.png'),
        ('MF', 'Saint Martin', 590, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Local_flag_of_the_Collectivity_of_Saint_Martin.svg/300px-Local_flag_of_the_Collectivity_of_Saint_Martin.svg.png'),
        ('PM', 'Saint Pierre and Miquelon', 508, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Armoiries_SaintPierreetMiquelon.svg/165px-Armoiries_SaintPierreetMiquelon.svg.png'),
        ('VC', 'Saint Vincent and the Grenadines', 1784, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/270px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png'),
        ('WS', 'Samoa', 684, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/188px-Flag_of_Samoa.svg.png'),
        ('SM', 'San Marino', 378, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/188px-Flag_of_San_Marino.svg.png'),
        ('ST', 'Sao Tome and Principe', 239, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg/188px-Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg.png'),
        ('SA', 'Saudi Arabia', 966, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/188px-Flag_of_Saudi_Arabia.svg.png'),
        ('SN', 'Senegal', 221, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/188px-Flag_of_Senegal.svg.png'),
        ('RS', 'Serbia', 381, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/188px-Flag_of_Serbia.svg.png'),
        ('CS', 'Serbia and Montenegro', 381, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_Serbia_and_Montenegro_%281992%E2%80%932006%29.svg/225px-Flag_of_Serbia_and_Montenegro_%281992%E2%80%932006%29.svg.png'),
        ('SC', 'Seychelles', 248, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/188px-Flag_of_Seychelles.svg.png'),
        ('SL', 'Sierra Leone', 232, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/188px-Flag_of_Sierra_Leone.svg.png'),
        ('SG', 'Singapore', 65, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/188px-Flag_of_Singapore.svg.png'),
        ('SX', 'Sint Maarten', 721, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Sint_Maarten.svg/188px-Flag_of_Sint_Maarten.svg.png'),
        ('SK', 'Slovakia', 421, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/188px-Flag_of_Slovakia.svg.png'),
        ('SI', 'Slovenia', 386, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/188px-Flag_of_Slovenia.svg.png'),
        ('SB', 'Solomon Islands', 677, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/188px-Flag_of_the_Solomon_Islands.svg.png'),
        ('SO', 'Somalia', 252, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/188px-Flag_of_Somalia.svg.png'),
        ('ZA', 'South Africa', 27, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/188px-Flag_of_South_Africa.svg.png'),
        ('GS', 'South Georgia and the South Sandwich Islands', 500, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg/195px-Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg.png'),
        ('SS', 'South Sudan', 211, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/188px-Flag_of_South_Sudan.svg.png'),
        ('ES', 'Spain', 34, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Bandera_de_Espa%C3%B1a.svg/188px-Bandera_de_Espa%C3%B1a.svg.png'),
        ('LK', 'Sri Lanka', 94, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/188px-Flag_of_Sri_Lanka.svg.png'),
        ('SD', 'Sudan', 249, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/188px-Flag_of_Sudan.svg.png'),
        ('SR', 'Suriname', 597, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/188px-Flag_of_Suriname.svg.png'),
        ('SJ', 'Svalbard and Jan Mayen', 47, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/188px-Flag_of_Norway.svg.png'),
        ('SZ', 'Swaziland', 268, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/188px-Flag_of_Eswatini.svg.png'),
        ('SE', 'Sweden', 46, 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/188px-Flag_of_Sweden.svg.png'),
        ('CH', 'Switzerland', 41, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/188px-Flag_of_Switzerland_%28Pantone%29.svg.png'),
        ('SY', 'Syria', 963, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/300px-Flag_of_Syria.svg.png'),
        ('TW', 'Taiwan, Province of China', 886, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/188px-Flag_of_the_Republic_of_China.svg.png'),
        ('TJ', 'Tajikistan', 992, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/188px-Flag_of_Tajikistan.svg.png'),
        ('TZ', 'Tanzania, United Republic of', 255, ''),
        ('TH', 'Thailand', 66, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/188px-Flag_of_Tanzania.svg.png'),
        ('TL', 'Timor-Leste', 670, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/188px-Flag_of_East_Timor.svg.png'),
        ('TG', 'Togo', 228, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/188px-Flag_of_Togo.svg.png'),
        ('TK', 'Tokelau', 690, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/188px-Flag_of_Tokelau.svg.png'),
        ('TO', 'Tonga', 676, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/188px-Flag_of_Tonga.svg.png'),
        ('TT', 'Trinidad and Tobago', 1868, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/188px-Flag_of_Trinidad_and_Tobago.svg.png'),
        ('TN', 'Tunisia', 216, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/188px-Flag_of_Tunisia.svg.png'),
        ('TR', 'Turkey', 90, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/188px-Flag_of_Turkey.svg.png'),
        ('TM', 'Turkmenistan', 7370, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/180px-Flag_of_Turkmenistan.svg.png'),
        ('TC', 'Turks and Caicos Islands', 1649, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/195px-Flag_of_the_Turks_and_Caicos_Islands.svg.png'),
        ('TV', 'Tuvalu', 688, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/188px-Flag_of_Tuvalu.svg.png'),
        ('UG', 'Uganda', 256, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/188px-Flag_of_Uganda.svg.png'),
        ('UA', 'Ukraine', 380, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/188px-Flag_of_Ukraine.svg.png'),
        ('AE', 'United Arab Emirates', 971, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/188px-Flag_of_the_United_Arab_Emirates.svg.png'),
        ('GB', 'United Kingdom', 44, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/188px-Flag_of_the_United_Kingdom_%281-2%29.svg.png'),
        ('US', 'United States', 1, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg/188px-Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg.png'),
        ('UM', 'United States Minor Outlying Islands', 1, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg/188px-Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg.png'),
        ('UY', 'Uruguay', 598, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/188px-Flag_of_Uruguay.svg.png'),
        ('UZ', 'Uzbekistan', 998, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/188px-Flag_of_Uzbekistan.svg.png'),
        ('VU', 'Vanuatu', 678, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/188px-Flag_of_Vanuatu.svg.png'),
        ('VE', 'Venezuela', 58, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/188px-Flag_of_Venezuela.svg.png'),
        ('VN', 'Vietnam', 84, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/188px-Flag_of_Vietnam.svg.png'),
        ('VG', 'Virgin Islands, British', 1284, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/195px-Flag_of_the_British_Virgin_Islands.svg.png'),
        ('VI', 'Virgin Islands, U.s.', 1340, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/188px-Flag_of_the_United_States_Virgin_Islands.svg.png'),
        ('WF', 'Wallis and Futuna', 681, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Flag_of_Wallis_and_Futuna.svg/195px-Flag_of_Wallis_and_Futuna.svg.png'),
        ('EH', 'Western Sahara', 212, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg/300px-Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg.png'),
        ('YE', 'Yemen', 967, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/188px-Flag_of_Zimbabwe.svg.png'),
        ('ZM', 'Zambia', 260, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/188px-Flag_of_Zambia.svg.png'),
        ('ZW', 'Zimbabwe', 263, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/188px-Flag_of_Zimbabwe.svg.png');



CREATE TABLE tblRights(
    idRight INT NOT NULL AUTO_INCREMENT,
    dtRight VARCHAR(6) NOT NULL,
    PRIMARY KEY (idRight)
);


CREATE TABLE tblUser(
    idUsername VARCHAR(10) UNIQUE,
    dtFirstName VARCHAR(40) NOT NULL,
    dtLastName VARCHAR(40) NOT NULL,
    dtPassword VARCHAR(60) NOT NULL,
    dtEmail VARCHAR(50) NOT NULL,
    dtTelephone VARCHAR(9),
    dtPLZ VARCHAR(6) NOT NULL,
    dtHouseNR VARCHAR(3) NOT NULL,
    dtStreet VARCHAR(15) NOT NULL,
    fiCountry VARCHAR(5) NOT NULL,
    fiRight INT NOT NULL,
    PRIMARY KEY (idUsername),
    FOREIGN KEY (fiCountry) REFERENCES tblCountry (idCountry),
    FOREIGN KEY (fiRight) REFERENCES tblRights (idRight)
);

INSERT INTO tblUser (idUsername, dtFirstName, dtLastName, dtPassword, dtEmail, dtTelephone, dtPLZ, dtHouseNR, dtStreet, fiCountry, fiRight)
VALUES  ('admin', 'Admin', 'Admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'admin@admin.lu', '621 345 345', '1234', '3', 'Am Seif', 'LU', 1),
        ('staff' , 'Staff', 'Staff', '1562206543da764123c21bd524674f0a8aaf49c8a89744c97352fe677f7e4006', 'staff@staff.lu', '691 567 567', '1234', '3', 'Am Seif', 'LU', 2),
        ('user', 'User', 'User', '04f8996da763b7a969b1028ee3007569eaf3a635486ddab211d512c85b9df8fb', 'user@user.lu', '621 788 897', '1234', '3', 'Am Seif', 'LU', 3),
        ('ribpe261', 'Pedro', 'Ribeiro Costa', 'd9b5f58f0b38198293971865a14074f59eba3e82595becbe86ae51f1d9f1f65e', 'ribpe261@school.lu', '691 522 129', '1940', '274', 'route de Longwy', 'PT', 1),
        ('frith033', 'Thibaut', 'Friederici', 'd9b5f58f0b38198293971865a14074f59eba3e82595becbe86ae51f1d9f1f65e', 'frith033@school.lu', '691 703 747', '6724', '13', 'Rue des Foyers', 'LU', 1),
        ('friti725', 'Tim', 'Frisch', 'd9b5f58f0b38198293971865a14074f59eba3e82595becbe86ae51f1d9f1f65e', 'friti725@school.lu', '', '', '', '', 'LU', 1),
        ('guoka342', 'Guo', 'Kaidi', 'd9b5f58f0b38198293971865a14074f59eba3e82595becbe86ae51f1d9f1f65e', 'guoka342@school.lu', '', '', '', '', 'LU', 1),
        ('gammi625', 'Mihails', 'Gamass', 'd9b5f58f0b38198293971865a14074f59eba3e82595becbe86ae51f1d9f1f65e', 'gammi625@school.lu', '', '', '', '', 'LU', 1);



CREATE TABLE tblProduct(
    idProduct INT NOT NULL AUTO_INCREMENT,
    dtProduct VARCHAR(100),
    dtPrice INT NOT NULL,
    dtImage VARCHAR(200) NOT NULL,
    PRIMARY KEY (idProduct)
);